[global]
  sendAnonymousUsage = false

[log]
  level = "DEBUG" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format = "common"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.db]
    address = ":5432"
  [entryPoints.node]
    address = ":3000"
  [entryPoints.https]
    address = ":443"

[providers]
  [providers.file]
    filename = "/etc/traefik/traefik.config.toml"
    watch = true

[providers.docker]
  useBindPortIP = true
  exposedByDefault = false
  endpoint = "unix:///var/run/docker.sock"
  watch = true

[docker.tls]
  cert = "/certs/localhost.crt"
  key  = "/certs/localhost.key"
  ca   = "/certs/localCA.crt"
  insecureSkipVerify = true

[api]
  insecure = true
